---
address: 127.0.0.1
pid: tmp/pids/thin.pid
port: 4545
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []

environment: development
max_persistent_conns: 512
daemonize: true
chdir: /home/soundboss/soundboss/current
